# Generated by Django 5.0.3 on 2024-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='imag',
            new_name='image',
        ),
        migrations.AddField(
            model_name='recipes',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingrediant',
            field=models.CharField(default='', max_length=20),
        ),
    ]
